# This yaml file includes 3 sections:
# 1. Model weights: path to the model resource, including base model weights and fine-tuned CAP model weights.
# 2. Input resources: path to input data, including DNA sequence, ATAC-seq, and protein embeddings.
# 3. Inference configuration: configuration for the inference process.

# Model weights paths
model_resource:
  root: /content/model_weights
  base_weights: chromnitron_base.pt
  per_cap_lora_weights: CAPs

# Input resources paths
input_resource:
  root: /content/input_resources
  sequence: DNA_sequence # These could be .fa files or .zarr files. <assembly_name>.fa or <assembly_name>.zarr, if using .zarr a chrom.sizes file is required, stored as <assembly_name>.chrom.sizes. SeqToVec can generate .zarr and .chrom.sizes files from .fa files.
  atac: ATAC_seq # These are .bigwig or .zarr files from SeqToVec pipeline. <sample_name>.zarr. recommend using symlinks to avoid copying files over
  cap: CAP_embeddings # These are .npz file embeddings generated by SeqToVec pipeline from protein sequences. <CAP_name>.npz

# Inference configuration: input and output paths. Regions, cell types, and CAPs of interest
inference_config: 
  input: 
    root: /content/chromnitron/chromnitron/examples/inputs
    assembly: hg38 # Assembly name, used to find chrom.sizes file
    excluded_region_path: auto # automatically determined by assembly and downloaded from Boyle lab, auto format: <assembly_name>-blacklist.v2.bed.
    locus_list_path: locus.bed # Bed file
    celltype_list_path: celltype.txt # Text file, one cell type per line according to atac-seq sample names
    cap_list_path: cap.txt # Text file, one CAP per line
  inference:
    enable: True
    use_finetune: auto # If auto, use finetuned model if available, otherwise use base model
    batch_size: 8 # Batch size for inference
    num_workers: 8 # Number of cpu workers for inference
  output: 
    path: /content/chromnitron_output # Directory to save output files
  post_processing:
    enable: True
    valid_margin: 1024 # Valid margin is removed from each side of the prediction to keep the prediction within the valid region
    store_bigwig: True # Whether to store bigwig files
    store_zarr: True # Whether to store zarr files
    peak_calling: True # Whether to call peaks
